name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.REPO_TOKEN }}
        issue-message: 'Hello folk!! All the best.'
        pr-message: 'Hello folk!! All the best.'
